version: "3.8"

services:
  service:
    image: node:14.17.5-alpine
    command: sh -c "yarn install"
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "yarn install && yarn start"
    ports:
      - 3001:3001
    environment:
      PORT: 3001
      POSTGRES_PASSWORD: light
      POSTGRES_USER: warrior
      POSTGRES_DB: overloaded
      POSTGRES_HOST: db
    depends_on:
      - db

  db:
    image: postgres:13.4
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/db_seed.sql:/docker-entrypoint-initdb.d/db_seed.sql
    environment:
      POSTGRES_PASSWORD: light
      POSTGRES_USER: warrior
      POSTGRES_DB: overloaded
    ports:
      - 5432:5432

volumes:
  postgres-data:
