# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test Pull Request

on:
  push:
    branches: [ kfb/**, bj/**, nk/**, dv/** ]

jobs:
  check-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: 14.17.5
        cache: 'yarn'
    
    - name: Install Dependencies
      run: yarn install
      
    - name: Cache Node Modules
      uses: actions/cache@v2.1.6
      env:
        cache-name: cache-node-modules
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Check Lint
      run: yarn lint

  check-code-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: 14.17.5
        cache: 'yarn'
    
    - name: Install Dependencies
      run: yarn install

    - name: Cache Node Modules
      uses: actions/cache@v2.1.6
      env:
        cache-name: cache-node-modules
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Check Code Format
      run: yarn format-check

  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: 14.17.5
        cache: 'yarn'
    
    - name: Install Dependencies
      run: yarn install

    - name: Run tests
      run: yarn test --coverage
